### ISSUE TITLE
Unable to extract download.

### ISSUE THREAD

**Issue by pingevt** [pantheon-se/node-composer#1]
I'm currently running into an error and not sure how to debug it further. I am unable to extract the download. While running `composer install` I get this error:

>  An error occurred while extracting NodeJS (/Users/peteinge/Sites/panth-github-actions/vendor/node-v14.19.0-darwin-x64.tar.gz) to /Users/peteinge/Sites/panth-github-actions/vendor/node-v14.19.0-darwin-x64. Error: tar: Error opening archive: Failed to open ' /Users/peteinge/Sites/panth-github-actions/vendor/node-v14.19.0-darwin-x64.tar.gz -C '/Users/peteinge/Sites/panth-github-actions/vendor/node-v14.19.0-darwin-x64' --strip 1'

The download looks to be successful. Running the tar command directly in the command line after seems to always work.

At first, I thought it was just a permissions issue while running in composer, so just messing around I changed the file permissions after download to 0777. And still get the error.

I am trying to use the 2.x-dev version on a new Drupal site from Pantheon. Currently Drupal 9.4.2. And Composer 2.3.7 and running on a Mac, 10.15.7.  Any thoughts or if you need any more info, please let me know.

I've been playing around with Github Actions and deploying to pantheon with Integrated composer. We use Gulp to process our css and js. We've been using CircleCi for a few years now and trying to figure out new options with Pantheon's Integrated Composer.

Thanks in advance for any help.

**Comment by kyletaylored** [comment]
Thanks Pete! Yes, this is an active bug I'm working on right now. It seems like there is a permission issue during the actual extraction, which does not add execute permissions on the actual files, so I'm working on figuring out how and why that happens. Will definitely keep you updated!

**Comment by pingevt** [comment]
Great to hear! Thanks Kyle - looking forward to any updates and let me know if I can help out with anything.

**Comment by kyletaylored** [comment]
Alright, I finally have it fixed! I'm running into a new issue unrelated to this, so I'm going to close this one, but keep opening new issues when you find them.

You'll want to keep using v2 of this package. The bug I'm running into now happens when I push to a Pantheon site repo, there's an "array to string conversion" error, but doesn't give me a stack trace, so I'm trying to replicate it locally.

**Comment by kalevitan** [comment]
Sorry to comment on a closed issue, but thought I'd share my findings on a similar issue. I'm using Docker Desktop with Lando on my Mac and the permissions issue was a result of using VirtioFS. Once I switched to another such a gRPC, the extraction eventually worked. https://github.com/docker/for-mac/issues/6614
