### ISSUE TITLE
Can we extend the untar process timeout for the node package?

### ISSUE THREAD

**Issue by kalevitan** [pantheon-se/node-composer#5]
My team and I are using node-composer with Docker Desktop and Lando, but some of us have experienced timeout issues locally when untaring the node package. I see that the `PantheonSalesEngineering\NodeComposer\Installer::untar()` method instantiates a Symfony Process, which has a default timeout of 60 seconds. Could we consider overriding this default by bumping it up a little to say, 200 seconds?

Thanks

**Comment by kyletaylored** [comment]
Bumped it to 3 minutes - let me know how that works!
